"""Email service for admin notifications and invite delivery."""
from email.message import EmailMessage
import smtplib
from typing import Iterable, Tuple, Optional

from src.config import settings
from src.utils.logging import logger


def send_invite_email(recipient: str, invite_codes: Iterable[str], sent_by: str) -> Tuple[bool, Optional[str]]:
    """Send invite code email to a recipient.

    Returns:
        Tuple of (success, error_message)
    """
    host = settings.smtp_host.strip()
    user = settings.smtp_user.strip()
    password = settings.smtp_password
    from_addr = (settings.smtp_from or settings.smtp_user).strip()
    port = settings.smtp_port

    if not host or not user or not password or not from_addr:
        return False, "SMTP is not fully configured"

    codes = [code.strip() for code in invite_codes if code and code.strip()]
    if not codes:
        return False, "No invite codes provided"

    msg = EmailMessage()
    msg["From"] = from_addr
    msg["To"] = recipient
    msg["Subject"] = "Your LogKeep Invite Code"

    codes_block = "\n".join(f"- {code}" for code in codes)
    plural = "code" if len(codes) == 1 else "codes"
    msg.set_content(
        f"Hello,\n\n"
        f"A LogKeep admin generated invite {plural} for you:\n\n"
        f"{codes_block}\n\n"
        f"Use this code during registration on LogKeep.\n\n"
        f"Generated by admin user: {sent_by}\n"
    )

    try:
        if port == 465:
            with smtplib.SMTP_SSL(host, port, timeout=20) as smtp:
                smtp.login(user, password)
                smtp.send_message(msg)
        else:
            with smtplib.SMTP(host, port, timeout=20) as smtp:
                smtp.ehlo()
                # StartTLS is expected for port 587.
                if port in (587, 25):
                    smtp.starttls()
                    smtp.ehlo()
                smtp.login(user, password)
                smtp.send_message(msg)

        logger.info("Invite email sent to %s", recipient)
        return True, None

    except Exception as exc:
        logger.error("Failed to send invite email to %s: %s", recipient, exc)
        return False, "Failed to send invite email"
